SERVICE_CATEGORIES = [
    ("ascenseurs", "Ascenseurs"),
    ("carrelage", "Carrelage"),
    ("clim-et-froid", "Climatisation et froid"),
    ("demolition", "Démolition"),
    ("depannage", "Dépannage"),
    ("electricite", "Électricité"),
    ("electricite-auto", "Électricité auto"),
    ("electro-menager", "Électroménager"),
    ("electronique", "Électronique"),
    ("encadrement", "Encadrement"),
    ("etancheite", "Étanchéité"),
    ("ferronnerie", "Ferronnerie"),
    ("jardinier", "Jardinage"),
    ("maconnerie", "Maçonnerie"),
    ("marbre", "Marbre"),
    ("mecanique", "Mécanique"),
    ("menuiserie", "Menuiserie"),
    ("parabole", "Parabole"),
    ("peinture", "Peinture"),
    ("piscine", "Piscine"),
    ("platrier", "Plâtrerie"),
    ("plomberie", "Plomberie"),
    ("pneumatiques", "Pneumatiques"),
    ("serrurerie", "Serrurerie"),
    ("surveillance-et-alarmes", "Surveillance et alarmes"),
    ("tapisserie", "Tapisserie"),
    ("transport", "Transport"),
    ("vitrerie-aluminium", "Vitrerie aluminium"),
]

